# Generated by Django 5.2.6 on 2025-10-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuil', models.CharField(max_length=11, unique=True)),
                ('mail', models.EmailField(max_length=120, unique=True)),
                ('direccion', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'Persona Física',
                'verbose_name_plural': 'Personas Físicas',
            },
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuil', models.CharField(max_length=11, unique=True)),
                ('mail', models.EmailField(max_length=120, unique=True)),
                ('direccion', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('razon_social', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Persona Jurídica',
                'verbose_name_plural': 'Personas Jurídicas',
            },
        ),
    ]
